#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 2 11:14:38 2022

@author: almakurmanova
"""

import numpy as np
from topas2numpy import read_ntuple
import matplotlib.pyplot as plt
import pandas as pd

#%% read data from simulation
path =('/Applications/topas/examples/TPS/test21_plus.header') 
data=read_ntuple(path)
data.dtype.names=('Position X (cm)',
 'Position Y (cm)',
 'Position Z (cm)',
 'Direction Cosine X',
 'Direction Cosine Y',
 'Energy (MeV)',
'Weight',
'Particle Type (in PDG Format)',
'Flag to tell if Third Direction Cosine is Negative (1 means true)',
'Flag to tell if this is the First Scored Particle from this History (1 means true)')
x=data['Position X (cm)']
y=data['Position Y (cm)']
z=data['Position Z (cm)']
cosX=data['Direction Cosine X']
cosY=data['Direction Cosine Y']
E=data['Energy (MeV)']
w=data['Weight']
ID=data['Particle Type (in PDG Format)']

#%%extracting data from proton
E_p=E[ID==2212] #ID particle
x_p=x[ID==2212]
y_p=y[ID==2212]
cosx_p=cosX[ID==2212]
cosy_p=cosY[ID==2212]

#%% Plot 
plt.figure()
plt.hist(E_p;label='Proton energy')
plt.xlabel('E')
plt.ylabel('N')
plt.legend()
plt.grid()
